### ISSUE TITLE
An unexpected error occurred.

### ISSUE THREAD

**Issue by jericjan** [AlphaDelta/WizTreeCompare#1]
I encountered this error while using your program. I am certain I used a past CSV and a future CSV.
https://pastebin.com/UE9DYij6

**Comment by AlphaDelta** [comment]
That's actually quite interesting, it looks like your dotnet environment doesn't recognize the string `2022/09/01 10:56:17` in your CSV as a valid date, yet I can parse it perfectly fine in my environment and on an online .NET 6 compiler.

Could you tell me your operating system, the locale of your system (if you have a locale, `Get-WinSystemLocale` in powershell), and your .NET version?

**Comment by jericjan** [comment]
Apparently, I didn't have a >=6.0.0 .NET Desktop Runtime so I installed that and I still got the same error.

My OS is Windows 10 v2004

My system locale is `1033 - en-US - English (United States)`

Here's my .NET info:
```
global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by AlphaDelta** [comment]
I think I may have fixed this, could you try again with the latest commit/[release](https://github.com/AlphaDelta/WizTreeCompare/releases/tag/v0.2.0)?

**Comment by jericjan** [comment]
Yeah that seems to have done it. Thanks!
